language: node_js

node_js:
   "10.9.0"

cache:
  directories:
    - node_modules
  yarn: true

install:
  - yarn install

script:
#  - yarn lint
 - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  email: hrupanjan@gmail.com
  name: Rupanjan Hari
  target-branch: master
  on:
    branch: development